/**
 * Created by lizhimin on 2017/12/8.
 */

'use strict';
const cwmDashboard = require('../cwmcontroller/dashboard');
const db = require("../lib/util").db;
exports.getDeviceStatus = function (req, res) {

};

exports.getStateSummary = function (req, res) {
    let orgId = req.body.orgId;
    let opeUserId = req.opeUserId;
    db.User.getUserRoleById(opeUserId, function (err, opeUser) {
        if (err) {
            return res.json({success: false, error: err});
        } else {
            cwmDashboard.getStateSummary(opeUser, orgId, (result)=> {
                return res.json(result);
            })
        }
    });


}
exports.getChannelUsedSummary = function (req, res) {
    let opeUserId = req.opeUserId;
    cwmDashboard.getChannelUsedSummary(req.body, opeUserId,(result)=> {
        return res.json(result);
    })
}
exports.getTopApUsage = function (req, res) {
    cwmDashboard.getTopApByUsage(req.body, (result)=> {
        return res.json(result);
    })
}
exports.getLatestEvents = function (req, res) {
    let opeUserId = req.opeUserId;
    cwmDashboard.getLatestEvents(req.body, opeUserId, (result)=> {
        return res.json(result);
    })
}
exports.getClientInfos = function (req, res) {
    let opeUserId = req.opeUserId;
    cwmDashboard.getClientInfos(req.body, opeUserId, (result)=> {
        return res.json(result);
    })
}
exports.getBlockedClientInfos = function (req, res) {
    let opeUserId = req.opeUserId;
    cwmDashboard.getBlockClient(req.body, opeUserId, (result)=> {
        return res.json(result);
    })
}
exports.getAccessPoints = function (req, res) {
    let opeUserId = req.opeUserId;
    let param = req.body.searchRule;
    let page = req.body.page;
    if (!page) {
        page = {start: 0, count: 50};
    } else {
        if (!page.start) page.start = 0;
    }
    cwmDashboard.getAccessPoints(param, page, opeUserId, function (err, data, count, online) {
        if (err) {
            return res.json({success: false, err: err});
        } else {
            return res.json({
                "success": true,
                "data": [{
                    "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                    "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                    "isDelete": 0,
                    "realDelete": 0,
                    "manageProcess": "",
                    "uuid": "5D77-30C0375D-11EABD34-5FF5",
                    "ip": "172.18.190.113",
                    "localipv6": "",
                    "sortIP": 2886909553,
                    "lanIP": "172.18.190.113",
                    "mac": "18:0f:76:2f:74:c0",
                    "firmware": "v2.00D01r045",
                    "backupFW": "",
                    "hardware": "A1",
                    "upTime": "239073",
                    "moduleType": "DAP-2680",
                    "bandType": 2,
                    "seriesName": "DAP-2680",
                    "modelOID": "1.3.6.1.4.1.171.10.37.60",
                    "lastUpdateTime": "2020-01-20T10:12:47.252Z",
                    "manageTime": "2020-01-20T10:09:25.907Z",
                    "status": "offline",
                    "channelList24Ghz": [0,
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11],
                    "channelList5Ghz": [0,
                        36,
                        40,
                        44,
                        48,
                        52,
                        56,
                        60,
                        64,
                        100,
                        104,
                        108,
                        112,
                        116,
                        132,
                        136,
                        140,
                        149,
                        153,
                        157,
                        161,
                        165],
                    "channelList5Ghz2": [0],
                    "keepAliveInterval": 60,
                    "statsInterval": "",
                    "sslVer": "",
                    "staToApRxDataBytes": 784096,
                    "apToStaTxDataBytes": 7127181,
                    "totalUsage": 7911277,
                    "cpuUsage": 42,
                    "memoryUsage": 27,
                    "wlan": [{
                        "ssid": "dlinktest",
                        "staToApRxDataBytes": 0,
                        "apToStaTxDataBytes": 0
                    },
                        {
                            "ssid": "paypaltest",
                            "staToApRxDataBytes": 0,
                            "apToStaTxDataBytes": 0
                        }],
                    "fixedChannel": [],
                    "fixedPower": [],
                    "channel24Ghz": 6,
                    "channel5Ghz": 132,
                    "channel5Ghz2": -1,
                    "power24Ghz": "100",
                    "power5Ghz": "100",
                    "power5Ghz2": "-1",
                    "location": "北京",
                    "name": "dap2680",
                    "supplierId": "",
                    "server": {
                        "channel5Ghz2": "-1",
                        "channel24Ghz": 6,
                        "channel5Ghz": 132,
                        "power24Ghz": "100",
                        "power5Ghz": "100",
                        "power5Ghz2": "-1",
                        "name": "dap2680",
                        "location": "北京"
                    },
                    "aycnProcessing": "",
                    "RFStatus": "",
                    "profile": {
                        "bandwidthOpt": 0,
                        "devSet": 4,
                        "performance": 0,
                        "schedule": 0,
                        "ssid": 3,
                        "vlan": 0,
                        "wirelessResource": 0,
                        "wlanPartition": 0
                    },
                    "isReboot": 0,
                    "webportNumber": "",
                    "_id": "e428d970-375d-11ea-8308-13b5c810e94f",
                    "index": 1,
                    "network": "Network1",
                    "schoolId": "",
                    "client": 0,
                    "percentUsage": "99.24"
                },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": "",
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "172.18.190.222",
                        "localipv6": "",
                        "sortIP": 2886909662,
                        "lanIP": "172.18.190.222",
                        "mac": "40:9b:cd:0c:65:50",
                        "firmware": "v2.00D01r045",
                        "backupFW": "",
                        "hardware": "A1",
                        "upTime": "2060250",
                        "moduleType": "DAP-2680",
                        "bandType": 2,
                        "seriesName": "DAP-2680",
                        "modelOID": "1.3.6.1.4.1.171.10.37.60",
                        "lastUpdateTime": "2020-01-21T09:41:47.601Z",
                        "manageTime": "2020-01-21T06:16:28.299Z",
                        "status": "online",
                        "channelList24Ghz": [0,
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11],
                        "channelList5Ghz": [0,
                            36,
                            40,
                            44,
                            48,
                            52,
                            56,
                            60,
                            64,
                            100,
                            104,
                            108,
                            112,
                            116,
                            132,
                            136,
                            140,
                            149,
                            153,
                            157,
                            161,
                            165],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": 60,
                        "statsInterval": "",
                        "sslVer": "bf:7f:4d:e7:5e:b0:72:6a:20:4e:5f:3f:4b:df:c8:44",
                        "staToApRxDataBytes": 6159084,
                        "apToStaTxDataBytes": 60504,
                        "totalUsage": 60504,
                        "cpuUsage": 5,
                        "memoryUsage": 27,
                        "wlan": [{
                            "ssid": "dlinktest111",
                            "staToApRxDataBytes": 0,
                            "apToStaTxDataBytes": 0
                        },
                            {
                                "ssid": "paypaltest",
                                "staToApRxDataBytes": 0,
                                "apToStaTxDataBytes": 60504
                            }],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": 1,
                        "channel5Ghz": 132,
                        "channel5Ghz2": -1,
                        "power24Ghz": "100",
                        "power5Ghz": "100",
                        "power5Ghz2": "-1",
                        "location": "劍閣崢嶸而崔嵬",
                        "name": "dap2680繁體中文",
                        "supplierId": "",
                        "server": {
                            "channel5Ghz2": "-1",
                            "channel24Ghz": 1,
                            "channel5Ghz": 132,
                            "power24Ghz": "100",
                            "power5Ghz": "100",
                            "power5Ghz2": "-1",
                            "name": "dap2680繁體中文",
                            "location": "劍閣崢嶸而崔嵬"
                        },
                        "aycnProcessing": "",
                        "RFStatus": "",
                        "profile": {
                            "bandwidthOpt": 0,
                            "devSet": 6,
                            "performance": 0,
                            "schedule": 0,
                            "ssid": 4,
                            "vlan": 0,
                            "wirelessResource": 0,
                            "wlanPartition": 0
                        },
                        "isReboot": 0,
                        "webportNumber": "",
                        "_id": "f27f09a0-3b6c-11ea-a735-5128a438ef9a",
                        "index": 2,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 1,
                        "percentUsage": "0.76"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.1",
                        "localipv6": "0:0:0:0:2582:3fc9:af00:add2",
                        "sortIP": 3232258561,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:00",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:23.383Z",
                        "manageTime": "2020-01-21T09:40:50.054Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_0",
                        "name": "Agent_1",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_1",
                            "location": "Location_0"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "1bcb2170-3c32-11ea-ab22-a72995ef408b",
                        "index": 3,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.2",
                        "localipv6": "0:0:0:0:e3d8:fe3d:d912:7de8",
                        "sortIP": 3232258562,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:18",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:10.791Z",
                        "manageTime": "2020-01-21T09:40:52.052Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_1",
                        "name": "Agent_2",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_2",
                            "location": "Location_1"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "1cfc0050-3c32-11ea-ab22-a72995ef408b",
                        "index": 4,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.3",
                        "localipv6": "0:0:0:0:79b8:7cf1:5ad7:c63e",
                        "sortIP": 3232258563,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:30",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:23.377Z",
                        "manageTime": "2020-01-21T09:40:26.838Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_2",
                        "name": "Agent_3",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_3",
                            "location": "Location_2"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "0df4a670-3c32-11ea-ab22-a72995ef408b",
                        "index": 5,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.4",
                        "localipv6": "0:0:0:0:1c7b:f915:46e4:c536",
                        "sortIP": 3232258564,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:48",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:16.887Z",
                        "manageTime": "2020-01-21T09:40:40.994Z",
                        "status": "offline",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_3",
                        "name": "Agent_4",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_4",
                            "location": "Location_3"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "1664af30-3c32-11ea-ab22-a72995ef408b",
                        "index": 6,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.5",
                        "localipv6": "0:0:0:0:6e88:310b:1ad4:1cb7",
                        "sortIP": 3232258565,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:60",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:17.348Z",
                        "manageTime": "2020-01-21T09:40:27.846Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_4",
                        "name": "Agent_5",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_5",
                            "location": "Location_4"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "0e8e9c80-3c32-11ea-ab22-a72995ef408b",
                        "index": 7,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.6",
                        "localipv6": "0:0:0:0:81ea:312e:ff1b:6954",
                        "sortIP": 3232258566,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:78",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:00.188Z",
                        "manageTime": "2020-01-21T09:40:23.829Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_5",
                        "name": "Agent_6",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_6",
                            "location": "Location_5"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "0c298360-3c32-11ea-ab22-a72995ef408b",
                        "index": 8,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.7",
                        "localipv6": "0:0:0:0:f56b:2b9b:801:a220",
                        "sortIP": 3232258567,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:90",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:14.315Z",
                        "manageTime": "2020-01-21T09:40:36.939Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_6",
                        "name": "Agent_7",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_7",
                            "location": "Location_6"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "13fa17d0-3c32-11ea-ab22-a72995ef408b",
                        "index": 9,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.8",
                        "localipv6": "0:0:0:0:d47c:4b74:eeac:a307",
                        "sortIP": 3232258568,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:a8",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:41:57.168Z",
                        "manageTime": "2020-01-21T09:40:24.157Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_7",
                        "name": "Agent_8",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_8",
                            "location": "Location_7"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "0c5b8fe0-3c32-11ea-ab22-a72995ef408b",
                        "index": 10,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.9",
                        "localipv6": "0:0:0:0:3e12:8be3:bb4b:b1d",
                        "sortIP": 3232258569,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:c0",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:07.768Z",
                        "manageTime": "2020-01-21T09:40:28.896Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_8",
                        "name": "Agent_9",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_9",
                            "location": "Location_8"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "0f2ed420-3c32-11ea-ab22-a72995ef408b",
                        "index": 11,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    },
                    {
                        "orgId": "e9cb0960-35e2-11ea-9c86-19806bcb743c",
                        "networkId": "5d781b20-375d-11ea-bd34-5ff5e33e7585",
                        "isDelete": 0,
                        "realDelete": 0,
                        "manageProcess": null,
                        "uuid": "5D77-30C0375D-11EABD34-5FF5",
                        "ip": "192.168.90.10",
                        "localipv6": "0:0:0:0:da3a:daa8:4ed6:b413",
                        "sortIP": 3232258570,
                        "lanIP": "172.18.190.36",
                        "mac": "00:01:02:03:5:d8",
                        "firmware": "0",
                        "backupFW": "0",
                        "hardware": "C",
                        "upTime": null,
                        "moduleType": "DAP-2720",
                        "bandType": 3,
                        "seriesName": "DAP-2720C",
                        "modelOID": "1.3.6.1.4.1.171.10.37.65",
                        "lastUpdateTime": "2020-01-21T09:42:05.752Z",
                        "manageTime": "2020-01-21T09:40:43.984Z",
                        "status": "boarding",
                        "channelList24Ghz": [0],
                        "channelList5Ghz": [0],
                        "channelList5Ghz2": [0],
                        "keepAliveInterval": null,
                        "statsInterval": null,
                        "sslVer": "0",
                        "staToApRxDataBytes": null,
                        "apToStaTxDataBytes": null,
                        "totalUsage": null,
                        "cpuUsage": 0,
                        "memoryUsage": 0,
                        "wlan": [],
                        "fixedChannel": [],
                        "fixedPower": [],
                        "channel24Ghz": null,
                        "channel5Ghz": null,
                        "channel5Ghz2": null,
                        "power24Ghz": null,
                        "power5Ghz": null,
                        "power5Ghz2": null,
                        "location": "Location_9",
                        "name": "Agent_10",
                        "supplierId": null,
                        "server": {
                            "channel24Ghz": null,
                            "channel5Ghz": null,
                            "channel5Ghz2": null,
                            "power24Ghz": null,
                            "power5Ghz": null,
                            "power5Ghz2": null,
                            "name": "Agent_10",
                            "location": "Location_9"
                        },
                        "aycnProcessing": null,
                        "RFStatus": null,
                        "profile": {

                        },
                        "isReboot": 0,
                        "webportNumber": null,
                        "_id": "182d1320-3c32-11ea-ab22-a72995ef408b",
                        "index": 12,
                        "network": "Network1",
                        "schoolId": "",
                        "client": 0,
                        "percentUsage": "0.00"
                    }],
                "total": 12,
                "online": 10
            });
            //return res.json({success: true, data: data, total: count, online: online});
        }
    })
}
//ap traffice useage
exports.getAllUsageData = function (req, res) {
    let opeUserId = req.opeUserId;
    let param = req.body.searchRule;
    let time = req.body.time;
    cwmDashboard.getAllUsageData(param, time, opeUserId, function (err, data) {
        if (err) {
            return res.json({success: false, err: err});
        } else {
            return res.json({success: true, data: data});
        }
    })

}
exports.getUsageDataByAP = function (req, res) {
    let mac = req.body.mac;
    let time = req.body.time;
    cwmDashboard.getUsageDataByAP(mac, time, function (err, data) {
        if (err) {
            return res.json({success: false, err: err});
        } else {
            return res.json({success: true, data: data});
        }
    })

}

