/**
 * Created by lizhimin on 2018/11/7.
 */
const lang = {
    login:{login: {
        title: 'CWM v2.0 for Login',
        welcome: "Welcome to",
        login: "Login",
        active: "Active",
        modify: "Modify",
        signup: "Sign up",
        rememer: "Remember me",
        forgotpass: "Forgot password?",
        loginAcc: "Login to your account",
        haveNoAcc: "Do not have an account?",
        haveAcc: "Already have an account?",
        welcom: "Welcome to",
        signUp: "Sign up for free",
        user: "Your E-mail / UserName",
        pass: "Your password",
        captcha: "Please input the captcha",
        next: "Next",
        reset: "Reset",
        name: "Pick a username",
        email: "Your E-mail",
        newPass: "Create a password",
        rePass: "Confirm password",
        needChange: "You need to change your password after the first login.",
        csActive: "The CWM coreserver has not been activated. Activate the server before configuring CWM.",

        forgot: {
            title: 'Forgot Password',
            info: "User Info",
            identity: "Authentication",
            set: "Set New Password",
            step1: "Enter your email address that you used to register. We'll send you an email with your username and a link to reset your password.",
            step2_1: " an email has been sent to",
            step2_2: "please check your email...",
            step3: "Your password has been reset, please login using your new password.",
            re: "Reset",
        }
    },
        invalid: {
            captchaMatch: 'Invalid captcha.',
            captchaError: "Captcha error",
            userName: 'Invalid email address or username, username is between 3~32,can only consist of underlines, letters and numbers.',
            password: 'The length is between 5~16.',
            passwordError: 'Username or password error.',
            email: "Invalid email address",
            emailNotExist: "This email does not exist",
            passNotsame: "The password is different from the confirmation password",
            minLen5: "The min length is 5",
            invalid: "Invalid Value",
            domain: "Invalid SMTP domain name",
            portnumber: "Port should be numeric types",
            pass: "Invalid password (ASCII only)",
            passError: "This password is not correct",
            passResetFailed: "Password reset has failed",
            strongPass: "Strong password consisting of 5 - 16 characters is required.  Combine uppercase letters, lowercase, letters, numbers and symbols.  Do not include common words or names."

        },
        license: {
            title: "Please input activation info",
            entermac: "MAC Address",
            activeCode: "Activation code",
            license: "License No."
        }},
    Disable: "Disabled",
    column: {
        moduleType: "Model Type",
        bandType: "Band Type",
        hardware: "HW Version",
        desc: "Description",
        userName: "Username",
        email: "Email",
        loginStatus: "Login Status",
        role: "Role",
        privilege: "Privilege Status",
        createTime: "Time of Creation",
        lastLogin: "Last Login Time",
        profile: 'Profile',
        action: "Action",
        status: "Status",
        name: "Name",
        ip: "Local IP Address",
        localipv6: 'Local IPv6 Address',
        lanIP: "NAT IP Address",
        ipv4: "IP Address",
        ipv6: "IPv6 Address",
        mac: "MAC Address",
        firmware: "FW Version",
        backupfw: "Backup FW Version",
        manageTime: "Managed Time",
        unmanageTime: "Unmanaged Time",
        no: "No.",
        location: "Location",
        network: "Network",
        client: "Client",
        channel24Ghz: "Channel 2.4G",
        channel5Ghz: "Channel 5G",
        channel5Ghz2: "Channel 5G 2nd",
        channel: "Channel",
        power24Ghz: "Power 2.4G",
        power5Ghz: "Power 5G",
        power5Ghz2: "Power 5G 2nd",
        totalUsage: "Traffic Usage",
        percentUsage: "Traffic Usage(%)",
        cpuUsage: "CPU Usage(%)",
        memoryUsage: "Memory Usage(%)",
        lastUpdateTime: "Last Seen",
        sysUpTime: "Uptime",
        download: "Download",
        upload: "Upload",
        usage: "Usage",
        authType: "Auth Type",
        os: "OS",
        hostName: "Host Name",
        rssi: "RSSI (dBm)",
        snr: "SNR (dB)",
        radioType: "Radio Type",
        clientRadio: "Client Radio Type",
        apRadio: "AP Radio Type",
        apMAC: "AP MAC Address",
        isLegacy: "Client Legacy Status",
        band: "Band",
        bssid: "BSSID",
        ssid: "SSID",
        apState: 'State',
        nmsURL: "NMS URL",
        applyResult: "Apply Result",
        runTime: "Run Time",
        resultMsg: "Log Details",
        vlanVID: "VLAN VID",
        vlanName: "VLAN Name",
        tagPorts: "Tag VLAN Ports",
        untagPorts: "Untag VLAN Ports",
        portName: "Port Name",
        tagVID: "Tag VID",
        untagVID: "Untag VID",
        pvid: "PVID",
        type: "Type",
        downSpeed: "Downlink Speed",
        upSpeed: "Uplink Speed",
        modify: "Modify",
        delete: "Delete",
        index: "Index",
        security: "Security",
        accessControl: "Access Control",
        userAuth: "User Authentication",
        subnetMask: "Subnet Mask",
        passcode: "Passcode",
        modelFW: "Model Name / HW Version",
        firmwareFile: "Firmware File",
        ssidIndex: "SSID Index",
        days: "Day(s)",
        userLimit: "User Limit",
        lastActive: "Last Active Day",
        duration: "Duration",
        durationRemain: "Remaining Duration",
        creator: "Creator",
        timeFrame: "Time Frame",
        wireless: "Wireless",
        edit: "Edit",
        print: "Print",
        taskType: "Operation Type",
        eventType: "Event Type",
        logTime: "Log Time",
        receiveTime: 'Receive Time',
        time: "Time",
        result: "Result",
        message: "Message",
        facility: "Facility",
        severity: "Severity",
        euServer: "Directive Server",
        trapTime: "Time of Trap",
        snmpVersion: "SNMP Version",
        trapType: "Trap Type",
        trapMsg: "Trap Details",
        siteName: "Site Name",
        networkName: "Network Name",
        schoolId: "School ID",
        totalDevices: "Total Devices",
        onlineDevices: "Online Devices",
        clients: "Clients",
        export: "Export",
        copyFrom: "Copy From",
        discovery: "Discovery",
        supplierId: "Supplier",
        tender: "Tender"
    },

    org: {
        orgManage: "Organization Management",
        orgLeave: "Organization Level",
        role: "Role",
        networkNum: "Network Number",
        managedDev: "Managed Devices",
        SMTPServer: "SMTP Server",
        nmsUrl: "CoreServer Address",
        keepAlive: "Live Packet Interval",
    },
    common: {
        owner: "Owner",
        manager: "Manager",
        tag: "RO/RW",
        all: "All",
        info: "Info",
        warning: "Warning",
        critical: "Critical",
        event: "System Event",
        allSite: "All Sites",
        allNetwork: "All Networks",
        seeMore: "See More",
        add: "Add",
        create: "Create",
        save: "Save",
        update: "Update",
        modify: "Modify",
        apply: "Apply",
        refresh: "Refresh",
        clear: "Clear",
        view: "View",
        delete: "Delete",
        cancel: "Cancel",
        close: "Close",
        reset: "Reset",
        next: "Next",
        back: "Back",
        exit: "Exit",
        edit: "Edit",
        disabled: 'Disabled',
        online: "Online",
        offline: "Offline",
        boarding: "Boarding",
        reg: "Registration",
        unknown: "Unknown",
        blocked: "Blocked",
        ok: "OK",
        yes: "Yes",
        no: "No",
        new: "New",
        copy: "Copy",
        print: "Print",
        test: "Test",
        testing: "Testing",
        search: "Search",
        export: "Export",
        exportCSV: "Export CSV",
        processing: "Processing",
        total: "Total",
        site: "Sites",
        networks: "Networks",
        access: "Access Points",
        clients: "Clients",
        upload: "Upload",
        download: "Download",
        runStatus: "Run Status",
        notSupport: "n/a",
        notice: "Notice",
        confirm: "Confirm",
        totalItems: " Total Items",
        itemspage: "Items Per Page",
        noData: "No data found",
        ipDomainHolder: "IP address/Domain name"

    },
    invalid: {
        email: "Invalid email address",
        passNotsame: "Password specified is different from the confirmation password",
        minLen5: "Minimum length is 5",
        invalid: "Invalid Value",
        domain: "Invalid SMTP domain name",
        ipdomain: "Please specify a valid IP or domain name",
        portnumber: "Port should be a numeric value",
        pass: "Invalid password",
        passError: "This password is not correct",
        strongPass: "Strong password is required. Please specify a password between 5-16 characters long consisting of lowercase and uppercase alphabetic characters, numbers and symbols. Do not include common words or names.",
        siteEmpty: "The new sitename can't be empty.",
        nameExist: "Duplicate network name is forbidden.",
        mapNameExist: "Duplicate hot AP map name is forbidden.",
        mapName: "Valid map name length is 3-32 characters.",
        schoolIdExist: "Duplicate School ID is forbidden.",
        schoolIdInvalid: "School ID can only be a figure with a length of 6.",
        vidID: "A valid VLAN ID (VID) value is from 1-4094",
        vidExist: "VID already exist",
        vlanName: "Please specify a name for this VLAN",
        bandWidth: "A valid value for bandwidth is from 1-1300",
        downlinkSpeed: "A valid value for downlink speed is from 1-",
        uplinkSpeed: "A valid value for uplink speed is from 1-",
        userName: "Username can only consist of letters and numbers",
        password: 'Password can only consist of letters and numbers',
        ntpServer: "Please input a valid IP address for the NTP server",
        required: "*This field is required",
        supplierName: "Valid supplier name length is 3~32 characters.",
        year: "Invalid year",
        liaison: "Valid contact person length is 3~16 characters",
        telephone: "Invalid telephone",
        site: "Invalid site.",
        timeRangeOver: "Start time should be before end time, when is not over night",
        sysName: "Black spaces and symbols are not allowed as part of the device name.",
        blankInvalid: "Space is not allowed at the beginning or the end.",
        location: "Black spaces and symbols are not allowed as part of the location.",
        specialCharacter: "Name cannot contain symbols such as ~^*(){}|\"<>?/'\][`",
        ssidInvalid: "SSID can not contain unicode and special symbol \" \' \` & \\"
    },
    enum: {
        enable: "Enable",
        disable: "Disable"
    },
    menu: {
        summary: '',
        frontdesk: 'FrontDesk',
        dashboard: "Dashboard",
        overView: "Overview",
        siteAndNet: "Site and Network",
        accessPoint: "Access Point",
        wirelessClient: "Wireless Client",
        monitor: "Monitor",
        deviceList: "Device List",
        map: "MAP",
        notifications: "Notification",
        triggerSet: "Trigger Setting",
        notificationSet: "Notification Setting",
        notificationView: "Notification View",
        maintenance: "Batch Configuration",
        configuration: "Configuration",
        profile: "Profile Settings",
        firmware: "Firmware Upgrade",
        ssl: "SSL Certificate",
        paymentGateway: "Payment Gateway",
        singleConfiguration: "Single Configuration",
        report: "Report",
        hotTime: "Peak Network Activity",
        hotAP: "Most Active AP",
        hourly: "Hourly Network Activity",
        daily: "Daily Network Activity",
        userDemand: "User Demand",
        legacyClient: "Legacy Client",
        log: "Log",
        notificationLog: "Notification Log",
        traplog: "SNMP Traps",
        syslog: "Syslogs",
        systemlog: "System Event Log",
        devicelog: "Device Log",
        operatelog: "Operation Log",
        system: "System",
        suppliers: "Suppliers",
        network: "Create Profile",
        deviceManage: "Device Management",
        team: "User Management",
        ccTest: "CC test view",
        settings: "Settings",
        about: "About",
        printPreview:"Print Preview"
    },
    nav: {
        userProfile: "User Profile",
        logout: "Logout",
        about: "About",
        language: "Language",
        theme: "Theme",
        passModifyOK: "Password successfully modified.",
        baseInfoOK: "The basic information  successfully modified.",
        emailOK: "Email Address successfully modified.",
        passError: "Password is error.",
        baseInfoError: "",
        emailError: "Email is already exists."
    },

    content: {
        noRecord: "No records available to display."
    },
    // Dashboard
    dashboard: {
        T10ABU: "Information from the Last Hour",
        APChannel: "Channel Utilization",
        AP24Channel: "APs on 2.4GHz Channel",
        AP5Channel: "APs on 5GHz Channel",
        LE: "Last Events",
        lastHourNumber: "Number of Clients in the Last Hour vs Number of Clients in the Past 7 Days",
        lastHourTraffic: "Traffic Usage in the Last Hour vs Traffic Usage in the Past 7 Days",
        lastHourTrafficDownUp: "Downlink/Uplink Traffic Usage Structure in the Last Hour",
        lastHourTrafficSsid: "Traffic Usage Structure by SSID in the Last Hour"
    },

    // Monitor
    accessPoint: {
        usage: "Usage",
        searchBy: "Search By",
        linktoPage: "Link to Device Detail Page",
        detail: "Detail",
        ignoreDevice: 'Move to Unmanaged',
        reboot: 'Reboot',
        noAP: "No Access Points.",
        rebootTitle: "Reboot",
        rebootTip: "Are you sure you want to reboot this AP?",
        unmanagedTitle: "",


    },
    wireless: {
        clientMACAddr: "MAC Address",
        ipv4Addr: "IP Address",
        connectedClients: "Connected Clients",
        blockedClients: "Blocked Clients",
        All: "All Clients",
        CaptivePortal: "Captive Portal Clients",
        noBlockedClient: "No blocked clients exist yet.",
        blockFailed: "Cannot block client because it is over max. ACL numbers.(512 per radio)",
        failedReason: "The ACL number is more than 512 for this radio.",
        noConnectedClients: "No client connected yet.",
        deleteTitle: "Delete Passcode",
        blockTitle: "Block Client",
        blockTip: "Are you sure you want to block this Client?",
        unblockTitle: "Unblock Client",
        unblockTip: "Are you sure you want to unblock this Client?"
    },
    deviceDetail: {
        devInfo: "Device Information",
        devSetting: "Device Setting",
        clientInfo: "Clients Info",
        noClient: "No clients currently exist.",
        msgTrue: "Device Setting successfully saved",
        msgFalse: "Device Setting Failed"
    },

    // configuration

    configuration: {
        conf: "Configuration",
        profile: "Profile",
        able0: "Disabled",
        able1: "Enabled",
        noNetwork: "No existing network can be found.",
        noNetwork1: "<span>No Network yet</span><span>click \'<a ng-click=\"goToNetwork()\">HERE</a>\' to view</span>",
        saveOK: "Configuration successfully uploaded ",
        clearOK: "Schedule successfully Cleared ",
        noResult: "No result available yet",
        uplodConfiguration: "Upload Configuration",
        menu: {
            ssid: "SSID",
            vlan: "VLAN",
            bandwidthOpt: "Bandwidth Optimization",
            schedule: "Schedule",
            devSet: "Device Setting",
            performance: "Performance",
            wlanPartition: "WLAN Partition",
            wirelessResource: "Wireless Resource",
            fwUpgrade: "Firmware Upgrade",
            sslCertificate: "SSL Certificate",
            RFOptimization: "RF Optimization",
            reboot: "Reboot",
            reset: "Reset",
            backup: "Back up",
            restore: "Restore"
        },
        band1: "2.4GHz",
        band2: "5GHz",
        onOff0: "Off",
        onOff1: "On",
        // speed
        bps1: "Kbits/sec",
        bps2: "Mbits/sec",
        vlan: {
            vlanList: "VLAN List",
            portList: "Port List",
            modifyVLAN: "Add/Edit VLAN",
            pvidSetting: "PVID Setting",
            msgTrue: "VLAN status successfully saved",
            pvidMsgTrue: "PVID successfully saved"
        },
        perf: {
            on: "On",
            off: "Off",
            mode1: "Mixed 802.11n, 802.11g and 802.11b",
            mode2: "Mixed 802.11g and 802.11b",
            mode3: "802.11n Only",
            mode4: "Mixed 802.11n and 802.11a",
            mode5: "802.11a Only",
            mode6: "802.11n Only",
            mode7: "Mixed 802.11ac",
            // Channel width
            cw1: "20 MHz",
            cw2: "Auto 20/40 MHz",
            cw3: "Auto 20/40/80 MHz",
            beaconInvalid: "A valid value for beacon interval is from 40-500",
            dimInvalid: "A valid value for DTIM Interval is from 1-15",
            ackInvalid: "A valid value for ACK time out is from",
            multicastInvalid: "A valid value for maximum multicast bandwidth is from 1-1024",
            rtsInvalid: "A valid value for RTS length is from 256-2346",
            fragmentInvalid: "A valid value for fragment length is from 256-2346",
            msgTrue: "Performance configuration sucessfully saved"
        },
        band: {
            addBORule: "Add Bandwidth Optimization Rule",
            // type
            type1: "Allocate average bandwidth for each station",
            type2: "Allocate a specific bandwidth for this SSID",
            type4: "Allocate different bandwidths for 11a/b/g/n stations",
            type3: "Allocate the maximum bandwidth for each station",
            // SSIDIndex
            ssid0: "Primary",
            ssid1: "SSID 1",
            ssid2: "SSID 2",
            ssid3: "SSID 3",
            ssid4: "SSID 4",
            ssid5: "SSID 5",
            ssid6: "SSID 6",
            ssid7: "SSID 7",
            ssid16: "Primary",
            ssid17: "SSID 1",
            ssid18: "SSID 2",
            ssid19: "SSID 3",
            ssid20: "SSID 4",
            ssid21: "SSID 5",
            ssid22: "SSID 6",
            ssid23: "SSID 7",
            msgTrue: "Bandwidth optimization saved successfully.",
            alert1: "Please save your rule edits first.",
            alert2: "Uplink speed as specified in the rule must be smaller than the uplink bandwidth.",
            alert3: "Downlink speed as specified in the rule must be smaller than the downlink bandwidth."
        },
        schedule: {
            addScheduleRule: "Add Schedule Rule",
            // ssidIndex
            ssid0: "Primary SSID 2.4GHz",
            ssid1: "SSID 1 2.4GHz",
            ssid2: "SSID 2 2.4GHz",
            ssid3: "SSID 3 2.4GHz",
            ssid4: "SSID 4 2.4GHz",
            ssid5: "SSID 5 2.4GHz",
            ssid6: "SSID 6 2.4GHz",
            ssid7: "SSID 7 2.4GHz",
            ssid8: "Primary SSID 5GHz",
            ssid9: "SSID 1 5GHz",
            ssid10: "SSID 2 5GHz",
            ssid11: "SSID 3 5GHz",
            ssid12: "SSID 4 5GHz",
            ssid13: "SSID 5 5GHz",
            ssid14: "SSID 6 5GHz",
            ssid15: "SSID 7 5GHz",
            // week
            all: "All Week",
            week1: "Sun.",
            week2: "Mon.",
            week4: "Tue.",
            week8: "Wed.",
            week16: "Thu.",
            week32: "Fri.",
            week64: "Sat.",
            Immediate: "Immediate",
            SelectTime: "Select Time",
            msgTrue: "Schedule saved sucessfully.",
            alert1: "The time schedule of the same SSID may not overlap with each other.",
            alert2: "Please save your rule edits first.",
            maxRulesAlert: "One SSID can only set 16 Schedule rules. ",
            nameValid:"Schedule name can not contain unicode and special symbol \" \' \` & \\"
        },
        wlan: {
            intemalSC: "Internal Station Connection",
            primarySSID: "Primary SSID",
            multiSSID1: "Multi-SSID 1",
            multiSSID2: "Multi-SSID 2",
            multiSSID3: "Multi-SSID 3",
            multiSSID4: "Multi-SSID 4",
            multiSSID5: "Multi-SSID 5",
            multiSSID6: "Multi-SSID 6",
            multiSSID7: "Multi-SSID 7",
            con0: "Disabled",
            con1: "Enabled",
            con2: "Guest Mode",
            msgTrue: "WLAN Partition saved succesfully"
        },
        dev: {
            admin: "Admin",
            consoleSettings: "Console Settings",
            automaticTC: "Automatic Time Configuration",
            countrySetting: "Country Setting",
            s0: "Never",
            s1: "1 Mins",
            s2: "3 Mins",
            s3: "5 Mins",
            s4: "10 Mins",
            s5: "15 Mins",
            week1: "First",
            week2: "Second",
            week3: "Third",
            week4: "Fourth",
            week5: "Last",
            countryTip: "Due to regulatory concerns, if any devices in the group with the country configuration set as United States, Japan, Korea, or Israel, the configuration will fail.",
            ipdomain: "IP address / Domain name",
            msgTrue: "Device configuration successfully saved",
            daylight: "Enable Daylight Saving"
        },
        wireless: {
            agingOut: "Aging Out",
            connectionLimit: "Connection Limit",
            bandSteering: "Band Steering",
            agingOut1: "RSSI",
            agingOut2: "Data Rate",
            msgTrue: "Wireless resource configuration sucessfully saved",
            validValue: "A valid value for user limits is from 0-64"
        },
        ssid: {
            templateDel: "Delete the template",
            templateDown: "Download template",
            // title
            SSIDBroadcast: "SSID Broadcast",
            security: "Security",
            accessControl: "Access Control",
            userAuthentication: "User Authentication",
            wirelessSettings: "Wireless Settings",
            WPASettings: "Security Settings",
            primaryRSS: "Primary RADIUS Server Settings",
            backupRSS: "Backup RADIUS Server Settings(optional)",
            primaryASS: "Primary Accounting Server Settings",
            backupASS: "Backup Accounting Server Settings(optional)",
            enableWhiteList: "Enable White List",
            ipFilterSettings: "IP Filter Settings",
            ipInterfaceSettings: "IP Interface Settings",
            webRedirection: "Web Redirection",
            userPass: "Username/Password",
            splashPageCustomization: "Splash Page Customization",
            passcodeList: "Passcode List",
            remoteRadius: "Remote RADIUS",
            radiusServerSettings: "RADIUS Server Settings",
            secondary: "Secondary",
            third: "Third",
            ldap: "LDAP",
            pop3: "POP3",
            externalCaptivePortal: "External Captive Portal",
            // button
            preview: "Preview",
            uploadLoginFile: "Upload Login File",
            // characterSet
            characterSet1: "UTF-8",
            characterSet2: "GB2312",
            // authentication
            security1: "Open System",
            security2: "Shared Key",
            security4: "WPA-Personal",
            security5: "WPA-Enterprise",
            security6: "WPA2-Personal",
            security7: "WPA2-Enterprise",
            security8: "WPA-Auto-Personal",
            security9: "WPA-Auto-Enterprise",
            // security10: "dot1x",
            // key size
            ks0: "64 Bits",
            ks1: "128 Bits",
            keyType1: "ASCII",
            keyType2: "HEX",
            // encryption type (cipherType)
            cipher1: "Auto",
            cipher2: "AES",
            cipher3: "TKIP",
            cipher4: "WEP",

            // mac access control action
            action1: "Accept",
            action2: "Reject",
            action3: "Disabled",
            // authentication type
            authType0: "Disabled",
            authType1: "Web Redirection Only",
            authType2: "Username/Password",
            authType4: "Remote RADIUS",
            authType5: "LDAP",
            authType6: "POP3",
            authType7: "Passcode",
            authType8: "External Captive Portal",
            authType9: "MAC Address",
            authType10: "External Hotspot Portal",
            // IPIFIpFrom
            IPIFIpFrom1: "Static IP Address (manual)", // static
            IPIFIpFrom2: "Dynamic IP Address (DHCP)", // dynamic
            // POP3
            connectType0: "None", // none
            connectType1: "SSL/TLS", // ssl-tls
            // LDAP
            ldap0: "Simple",
            ldap1: "TLS",
            // Remote RADIUS
            radiusType0: "SPAP",
            radiusType1: "MS-CHAPv2",
            noticeMsg: "Use same setting for  {{ssidIndex}} / {{band}}?",
            noticeMsg1: "Create same setting for {{ssidIndex}} / {{band}}?",
            msgTrue: "SSID successfully saved",
            templateName: "Template Name",
            uploadFile: "Upload Login File",
            invalid1: "Please enter a value between 300-9999999",
            invalid2: "Valid passphrase length is 8-63 characters",
            invalidRadius: "Please specify a valid IP address for the RADIUS server",
            invalidPOP3: "Please specify a valid address for the POP3 server",
            invalidLDAP: "Please specify a valid address for the LDAP server",
            requireLDAPUser: "Please specify the username for the LDAP server",
            requireLDAPPass: "Please specify the password for the LDAP server",
            invalidPort: "A valid value for port is from 1-65535",
            invalidSecrete: "Password specified is not valid (Password length must be between 0-64 characters.)",
            maxMAC24: 'The max number of MAC address List for band 2.4GHz is 512,',
            maxMAC5: 'The max number of MAC address List for band 5GHz is 512,',
            idleTime: "Idle timeout is from 2-1440",
            macExisted: "This MAC address already exists",
            userExisted: "This Username already exists",
            invalidIP: "Please specify a valid IP address",
            invalidNetmask: "Please specify a valid subnet mask",
            invalidGateway: "Please specify a valid gateway",
            invalidDNS: "Please specify a valid DNS",
            ipFilterExist: "This IP filter has added already",
            invalidVLANGroup: "A valid value for VLAN Group is from 1-4094",
            invalidEcpserver: "External Captive Portal Server address must set to a valid domain name.",
            invalidRedirectionURL: "Please provide the web address",
            ssidExist: "This SSID already exists",
            ssidNameExist: "SSID names for same bands cannot be repeated.",
            uploadaclMore: "Upload failed, the number of entries in the MAC Address List cannot be more than 512.",
            uploadFileError: "Upload failed, the file contains errors or is not in the correct format.",
            uploadwhitelistMore: "Upload failed, the maximum number of entries in White List is 64.",
            aclMore: "The max. number of entries in the MAC Address List is more than 512.",
            templateIsDefault: "You cannot delete the default template.",
            templateIsUsed: "You cannot delete a template that is currently being used.",
            maxUsers: "The max. number of any Username/Password combination is 128,",
            maxIPFilters: "The max. number of entries in the IP Filters is 64,",
            maxWhiteLists: "The max. number of entries in the White List is 64,",
            invalidMAC: "Invalid MAC Address",
            userNameInvalid: "Space is not allowed at the beginning or the end.",
            invalidHex: "64 characters must be in hexadecimal",
            invalidHex1: "It is must be hexadecimal",
            passcodeSSIDMore: "Only one passcode authentication-type SSID can be set on the same band.",
            acl: "ACL",
            hostspotServer: "External Hotspot Portal",
            walledGarden: "Walled Garden",
            maxWalled: "The max. number of entries in the Walled Garden is 5,",
            invalidHotspotserver: "The External Hotspot Portal Server address must be set to a valid domain name.",
            accountServerSetting: "Account Server Setting",
            gardenIpExisted: "IThis P Address already exists in the Walled Garden",
            aclFileSize: "The max. file size is 100KB.",
            loginFileSize: "The max. file size is 2MB.",
            loginFileNameExist: "Template name already exists.",
            loginFileFormat: "The filename extension of Login file must be tar.",
            delSSIDTitle: 'Delete SSID',
            delSSIDTip: 'Are you sure you want to delete this ssid?',
        },
        rf: {
            rfOptimization: "RF Optimization",
            msgTrue: "RF optimization successfully saved"
        }
    },
    firmware: {
        firmware: "Firmware Upgrade",
        upload: "Upload firmware files for each model",
        noModel: "No model can be found",
        msgTrue: "Firmware upgrade successfully saved",
        clearOK: "Schedule successfully cleared ",
        msgFalse1: "Model type of the firmware file does not match model to be upgraded",
    },
    ssl: {
        ssl: "SSL Certificate",
        updateSSL: "Update SSL certificate",
        msgTrue: "SSL certificate successfully saved",
        msgFalse1: "The filename extension of the certificate and private key file must be pem.",
        msgFalse2: "Signature algorithm MUST be \"SHA256 with RSA encryption\", Key algorithm MUST be \"RSA Encryption\", Key length is at least 2048 bit and Validity MUST be 7300 days.",
        msgFalse3: "Database Error."
    },
    paymentGateway: {
        paymentSetting: "Payment Settings"
    },
    report: {
        trafficUsage: "Traffic Usage",
        uniqueClients: "Unique Clients",
        bigger: "Bigger",
        reset: "Reset",
        smaller: "Smaller",
        changeBmap: "Change Background Picture",
        exportPdf: "Export PDF",
        modifyThreshold: "Modify Threshold",
        dailyTitle: "Daily Stats in Wireless Network",
        dailyChartTitle: "Daily Traffic Usage vs Unique Clients",
        dailyUsage: "Traffic Usage",
        dailyUnitClients: "Unique Clients",
        hotTimeTitle: "Hot Time in Wireless Network",
        hotTimeChartTitle1: "Most Clients Hot Time According Past 7 Days Experience",
        hotTimeChartTitle2: "Most Traffic Usage Hot Time According Past 7 Days Experience",
        threshold: "Threshold",
        probability: "Probability",
        hourlyTitle: "Hourly Stats in Wireless Network",
        hourlyChartTitle1: "Hourly Unique Clients vs Past 7 Days Experiences",
        hourlyChartTitle2: "Hourly Traffic Usage vs Past 7 Days Experiences",
        hotAPHeader: "Maps of Most Active APs",
        hotAPTitle: "Most Active AP According to in the Past 7 Days",
        hotAPUniqueClientTitle: "Unique Client Average/High",
        hotAPTrafficUsageTitle: "Traffic Usage Average/High",
        hotAPTitleCreate: "Create Map of Most Active APs",
        hotAPTitleEdit: "Edit Map of Most Active APs",
        hotAPMapName: "Most Active APs Map Name",
        hotAPMapName_placeholder: "Ex. D-Link 3F",
        hotAPCustomize: "Customize the Map*",
        dragInfo1: "Your Picture Here",
        dragInfo2: "(file format *.png,*.jpg,up to 10M)",
        dragInfo3: "or",
        dragInfo4: "Click to",
        dragInfo5: "choose a picture",
        dragInfo6: "Drop Here",
        noMapInfo1: "Map of Most Active APs does not exist.",
        noMapInfo2: "Map of Most Active APs does not exist, please add Map of Most Active APs first.",
        noMapInfo3: "You can add a map file ",
        noMapInfo4: "here",
        delTitle: 'Delete Map',
        delTip: 'Are you sure you want to delete this map?',
        selCountInfo: "Selected Devices Count / Max:",
        picMaximum: "Failed to upload picture; picture size exceeds maximum size limit of 10M.",
        picType: "Failed to upload picture; picture file type invalid."
    },

    // Report
    // Log
    syslog: {
        syslogs: "Syslogs",
        captive: "Captive Portal Log",
        serverity: {
            All: "All Severity"
        },
        facility: {
            All: "All Facility"
        }
    },
    traplog: {
        version: {
            All: "All SNMP Versions"
        },
        type: {
            All: "All Generic Type"
        }
    },
    systemlog: {
        All: "All Event Type",
        logType1: "Device Management",
        logType2: "Synchronization",
        logType3: "Duplicate Task",
        logType4: "Timeout Task",
        logType5: "Invalid HTTP Message",
        logType6: "Initialization",
        logType7: "Validate Http Message"
    },
    devicelog: {
        All: "All Operation Type",
        syncConfig: "Synchronize Device Settings",
        profile: "Synchronize AP profile",
        setStatsInterval: "Set Statistics Interval",
        fwUpgrade: "Firmware Upgrade",
        sslCertificate: "SSL Certificate Upload",
        uploadCfg: "Upload Configuration",
        setApChannelNum: "Set AP Channel Number",
        setDeviceLocation: "Set Device Location",
        setDeviceName: "Set Device Name",
        setApPower: "Set AP Power",
        setKaInterval: "Set Keep-Alive Interval",
        removeManagedDevs: "Unmanage Device",
        addManageDevs: "Manage Device",
        deleteIgnorDev: "Delete Device",
        getNeighborApInfo: "Retrieve Neighbor AP Information ",
        reboot: "Reboot",
        unblockClient: "Unblock Client",
        blockClient: "Block Client",
        addAPAllowClient: "Add AP Allow Client",
        ddpDiscover: "DDP Discover",
        ddpv5L2: "DDPv5L2",
        ddpv5L34: "DDPv5L34",
        registerDevice:"Register Device"
    },
    // System
    license: {
        addLicense: "Add License"
    },
    deviceManage: {
        networks: "Networks",
        // tab 切换
        managed: "Managed",
        unmanaged: "Unmanaged",
        currentNet: "Current Network",
        reManaged: "Re-manage",
        // 按钮
        del: "Delete",
        removeToUnmanaged: "Move to Unmanaged",
        moveToManage: "Move to Managed",
        noIgnore: "No devices Unmanaged",
        delMsg: "Are you sure you want to delete this AP from CWM?",
        delMsg1: "Are you sure you want to delete these APs from CWM?",
        reManageMsg: "Are you sure you want to Manage this AP by network",
        reManageMsg1: "Are you sure you want to Manage these APs by network",
        noManaged: "No device managed yet",
        unmanageTip: "Are you sure you want to move this AP to Unmanaged?",
        unmanageTip1: "Are you sure you want to move these APs to Unmanaged?"

    },
    team: {
        // 权限
        "root admin": "Root admin",
        "root user": "Root user",
        "local admin": "Local admin",
        "local user": "Local user",
        "front desk user": "Front desk staff",
        "online users": "Online users",
        // 标题
        allUsers: "All Users",
        totalUsers: "Total Users",
        // tab 切换
        userStatus: "User Status",
        userPrivilege: "User Privilege",
        // 添加用户按钮
        addUser: "Add User",
        validPass: "The length is between 5~16.",
        validUsername: "Valid username length is 3-32 characters",
        delTitle: 'Delete User',
        delTip: 'Are you sure you want to delete this user?'
    },
    settings: {
        // tab 切换
        general: "General",
        connection: "Connection",
        smtp: "SMTP",
        dataBase: "Database",
        restapi: "REST API",
        restapikey: "REST API Key",
        generateKey: "Regenerate Key",
        restAPITitle:"Notice",
        restAPITip:"Are you sure you want to generate a new Key? If you do this,you should replace ",
        saveOK: "Successfully saved",
        // 标题
        customizedSetting: "Customized Setting",
        deviceSetting: "Device Setting",
        connectionSetting: "Connection Setting",
        updateSSLCertificate: "Update SSL Certificate",
        logBackup: "Log Backup",
        auth: "Authentication",
        smtpHost: "SMTP Host Address *",
        smtpHost_placeholder: "Host",
        smtpPort: "Port *",
        smtpPort_placeholder: "Port",
        fromAddr: "From Email Address *",
        fromAddr_placeholder: "From Email Address",
        fromName: "From Name *",
        fromName_placeholder: "From Name",
        securityType: "Security Type *",
        encoding: "Encoding Type *",
        userName: "Username *",
        userName_placeholder: "Username",
        pass: "Password *",
        pass_placeholder: "Password",
        testEmail: "Test Email",
        testEmail_placeholder: "Test Email",
        uploadKey: "Upload Key From File",
        uploadCert: "Upload Certificate From File",
        webPort: "Web Access Port",
        csPort: "CoreServer Access Port",
        webPort_holder: "Port",
        webAddr: "Web Access Address",
        devPort: "Device Access Port",
        devPort_holder: "Port",
        devAddr: "Device Access Address",
        kaInterval: "Live Packet Interval",
        captcha: " Login Captcha",
        logoFormat: "The logo file must be in PNG or JPG image file format",
        coreRestartInfo: "CWM Core server needs to be restarted if Device Access Address or Port has been changed.",
        webRestartInfo: "CWM Web server needs to be restarted if Web Access Address or Port has been changed.",
        orgName_label: "Org Name",
        orgName_placeholder: "Org Name",
        logo: "Logo",
        browser_holder: "Browser...",
        db: {
            autobackup: "Auto Backup",
            interval: "Auto Backup Interval Time",
            logbackupdesc: "As data is continuously being collected in the background, the amount of data saved will increase substantially over time. You can set up automatic backup of your data, and then delete it after backup is complete.",
            logbackupInterval: "",
            intervalMode1: "Days",
            intervalMode2: "Weeks",
            intervalMode3: "Months",
        },
        drag: "Drag & Drop",
        drop: "Drop Here",
        dragTip: "Logo File Here, or",
        browser: "Browser",
        wizard: "Wizard",
        supplierAdd: "Add Supplier",
        supplierEdit: "Supplier Edit"
    },
    about: {
        cwv: "Central WiFiManager Version",
        update: "Update Online",
        msgTrue: "Update Successfully",
        error1: "This is the latest version",
        error2: "Server Error : {{msg}}",
        band1: "single",
        band2: "dual",
        band3: "tri-band",
        band4: "selectable dual"
    },
    // 单独icon按钮提示信息 /  弹窗标题
    title: {
        search: "Search",
        global: "Global",
        notification: "Notification",
        viewOrg: "View Orgs",
        hide: "Hide",
        show: "Show",
        edit: "Edit",
        pause: "Pause",
        active: "Active",
        del: "Delete",
        copy: "Network Profile Copy From",
        view: "View",
        close: "Close",
        open: "Open",
        passHide: "Hide Password",
        passShow: "Show Password"
    },
    model: {},
    passcode: {
        unitMin: "Minute(s)",
        unitHour: "Hour(s)",
        unitDay: "Day(s)"
    },
    frontdesk: {
        frontdesk: "Front Desk",
        signOut: "Sign Out",
        generatePasscode: "Generate Passcode",
        viewEditDelete: "View / Edit / Delete",
        searchPasscode: "Search Passcode",
        allGroup: "All Networks",
        passcodeSettings: "Passcode Settings",
        searchCondition: "Search Condition",
        passcodeList: "Passcode List",
        duration: "Duration",
        passcode: "Passcode",
        passcodeq: "Passcode Quantity",
        ssidValid: "The SSID is required, this network has no SSID.",
        passcodeqValid: "A valid passcode quantity value is from 1~200",
        passcodelenValid: "The length of the passcode is 8",
        durationValid: "The duration must be between 1~180 day(s) or 1~4320 hour(s) or 1~259200 minute(s)",
        lastActivedaya: "Last Active Day",
        userLimit: "User Limit",
        userLimitValid: "The user limit must be between 1~32",
        paypalAccount: "Paypal Account",
        purchaseStat: "Purchase Station",
        purchaseTime: "Purchase Time",
        activeTime: "Active Time",
        ssid: "SSID",
        group: "Networks",
        hours: "Hour(s)",
        passcodeExist: "Passcode already exists",
        modifyTip: "Passcode cannot be modified in this state",
        deleteTitle: "Delete Passcode",
        deleteTip: "Are you sure you want to delete this Passcode?",
        deleteTips: "Are you sure you want to delete these Passcodes?"
    },

    // 弹窗
    userProfile: {
        userProfile: "User Profile",
        personalInformation: "Personal Information",
        security: "Security",
        changePhoto: "Change Photo",
        browse: "Browse",
        information: "Information",
        changePassword: "Change Password",
        changeEmail: "Change Email"
    },
    network: {
        column_version: "Version",
        newNetwork: "New Network",
        copyTitle: "Copy Profile From this Network",
        exportTitle: "Export Network Profile",
        delTitle: 'Delete Network',
        delTip: 'Are you sure you want to delete this network?',
    },
    addNetwork: {
        sys: "System Settings",
        edit: "Edit Probe",
        view: "View Probe",
        export: "Export Agent UUID",
        an: "Add Network",
        en: "Edit Network",
        nc: "Network Configurations",
        dsfn: "Discover Network Settings",
        d: "Discovery AP",
        wirelessSetting: "Wireless Settings",
        deviceSetting: "Device Settings",
        startDiscovery: "Start Discovery",
        discovering: "Discovery…",
        scanning: "Scanning in progress, please wait.",
        scanned: "Scan Finished",
        reDiscovery: "Re-Discovery",
        standalone: "Configurable",
        managed: "Managed",
        state0: 'Standalone',
        state1: 'Unregistered',
        state2: 'Boarding',
        state3: 'Managed',
        state4: 'Unmanaged',
        conflictIP: "Confict with another network\'s IP range.",
        noDevice: "No Device yet.",
        networkNameLen:"Valid network name length is 1-32."
    },
    addUser: {
        createUser: "Create User",
        userModify: "User Modifications",
    },
    // label 公共
    label: {
        // public
        name: "Name",
        username: "Username",
        password: "Password",
        email: "Email",
        location: "Location",
        description: "Description",
        server: "Server",
        port: "Port",
        code: "Code",
        options: "Options",
        selectAll: "Select All",
        band: "Band",
        hours: "Hours",
        index: "Index",
        // user profile
        telephone: "Telephone",
        newPassword: "New Password",
        repeatPassword: "Repeat Password",
        newEmailAddress: "New Email Address",
        // add network
        deviceAccessAddress: "Device Access Address",
        deviceAccessPort: "Device Access Port",
        site: "Site",
        networkName: "Network Name",
        ssidName: "SSID Name",
        security: "Security",
        ssidPassword: "SSID Password",
        country: "Country",
        timeZone: "Time Zone",
        layer: "Layer",
        setProfile: "Import Network Profile:",
        // add user
        privilege: "Privilege",
        privilegeStatus: "Privilege Status",
        // profile
        timeStart: "Time Start",
        applyStatus: "Apply Status",
        result: "Results",
        // ssid
        ssid: "SSID",
        characterSet: "Character Set",

        encryption: "Encryption",
        keySize: "Key Size",
        keyType: "Key Type",
        keyIndex: "Key Index",
        keyValue: "Key Value",
        charactersRequired: "Characters Required",
        encryptionType: "Encryption Type",
        groupKeyUI: "Group Key Update Interval",
        passphrase: "Passphrase",
        accountingMode: "Accounting Mode",
        accountingServer: "Accounting Server",
        accountingPort: "Accounting Port",
        accountingSecret: "Accounting Secret",
        action: "Action",
        macAddress: "MAC Address",
        uploadMACAddressList: "Upload MAC Address List",
        authenticationType: "Authentication Type",
        idleTimeout: "Idle Timeout",
        minutes: "Minute(s)",
        uploadWhiteListFile: "Upload Whitelist File",
        ipAddress: "IP Address",
        subnetMask: "Subnet Mask",
        IPIFStatus: "IPIF Status",
        VLANGroup: "VLAN Group",
        getIPAddressFrom: "Get IP Address From",
        gateway: "Gateway",
        dns: "DNS",
        website: "Website",
        chooseTemplate: "Choose Template",
        radius: "RADIUS",
        radiusServer: "RADIUS Server",
        radiusPort: "RADIUS Port",
        radiusSecret: "RADIUS Secret",
        remoteRadiusType: "Remote RADIUS Type",
        authenticationMode: "Authentication Mode",
        baseDN: "Base DN",
        accountAttribute: "Account Attribute",
        identity: "Identity",
        autoCopy: "Auto Copy",
        connectionType: "Connection Type",
        serverAddress: "Server Address",
        // VLAN
        vlanStatus: "VLAN Status",
        vlanID: "VLAN ID (VID)",
        vlanName: "VLAN Name",
        untag: "Untag",
        tag: "Tag",
        notMember: "Not Member",
        pvidAutoAssignStatus: "PVID Auto Assign Status",
        // bandwidth optimization
        enableBO: "Enable Bandwidth Optimization",
        bandwidth: "Bandwidth",
        speed: "Speed",
        downlink: "Downlink",
        uplink: "Uplink",
        ruleType: "Rule Type",
        ssidIndex: "SSID Index",
        // rf optimization
        adjustFrequency: "Adjust Frequency",
        autoCA: "Auto Channel Adjustment",
        autoPA: "Auto Power Adjustment",
        // schedule
        wirelessSchedule: "Wireless Schedule",
        day_s: "Day(s)",
        time_s: "Time(s)",
        startTime: "Start Time",
        endTime: "End Time",
        overNight: "Over Night",
        allWeek: "All Week",
        allDay: "All Day",
        selectDay_s: "Select Day(s)",
        selectTime_s: "Select Time(s)",
        // device setting
        consoleProtocol: "Console Protocol",
        timeOut: "Time Out",
        ntpServer: "NTP Server",
        selectCountry: "Select Country",
        externalSyslogServer: "External Syslog Server",
        // performance
        wireless: "Wireless",
        wirelessMode: "Wireless Mode",
        dataRate: "Data Rate",
        beaconInterval: "Beacon Interval",
        dtimInterval: "DTIM Interval",
        wmm: "Wi-Fi Multimedia",
        ackTimeOut: "ACK Timeout",
        shortGI: "Short GI",
        igmpSnooping: "IGMP Snooping",
        multicastRate: "Multicast Rate",
        multicastBC: "Multicast Bandwidth Control",
        maximumMB: "Maximum Multicast Bandwidth",
        htCoexistence: "HT20/40 Coexistence",
        transferDOTU: "Change DHCPOFFER from Multicast to Unicast",
        rtsLength: "RTS Length",
        fragmentLength: "Fragment Length",
        channelWidth: "Channel Width",
        // wlan partition
        linkIntegrity: "Link Integrity",
        ethernetToWA: "Ethernet to WLAN Access",
        // wireless resource
        aclRssiThreshold: "ACL RSSI Threshold",
        agingOut: "Aging Out",
        rssiThreshold: "RSSI Threshold",
        userLimit: "User Limit",
        preferred11n: "11n Preferred",
        networkUtilization: "Network Utilization",
        bandSteeringAge: "Band Steering Age",
        bandSteeringDifference: "Band Steering Difference",
        bandSteeringRefuse: "Band Steering Refuse Number",
        airtimeFairness: "Airtime Fairness",
        bandSteer: "Band Steering",
        // ssl certificate
        uploadCertificate: "Upload Certificate From File",
        uploadKey: "Upload Key From File",
        // payment gateway
        paypalCurrency: "PayPal Currency",
        paypalClientID: "PayPal Client ID",
        paypalSecret: "PayPal Secret",
        signature: "Signature",
        duration: "Duration",
        cost: "Cost",
        DSTStart: "DST Start (24HR)",
        DSTEnd: "DST End (24HR)",
        DSTOffset: "DST Offset (minutes)",
        accountStatus:"Account Server Status",
        serverAddress: "Server Address",
        sessionTime: "Session timeout"
    },
    supplier: {
        supplier: "Supplier",
        name: "Name",
        year: "Year",
        liaison: "Contact Person",
        tel: "Telephone",
        site: "Site",
        delTitle: "Delete Supplier",
        delTip: "Are you sure you want to delete this supplier?"
    }
}
module.exports = {
    lang
}